tinkoff:
#  figi: 'FUTNGM022500' # 'FUTIMOEXF000'
  instrument_id: afbc7c40-fe28-465b-80ee-2f047bd691e4 # NRG5
#  instrument_id: 962e2a95-02a9-4171-abd7-aa198dbe643a #GAZP


strategy:
  ema_fast_period: 9
  ema_slow_period: 21
  rsi_period: 14
  max_drawdown: 0.1
  daily_loss_limit: 0.02
  risk_per_trade: 0.01
  lot_size: 1
  max_contracts: 1
  commission_rate: 0.00025
  min_percent_for_interest: 0.4
  spread_ticks: 2
  stop_percent: 0.5

rsi:
  for_sell: 88
  for_buy: 12
  for_close:
    - 18
    - 82

take_profit:
  trailing_indent: 0.005
