tinkoff:
  figi: 'BBG004730RP0' # 'FUTIMOEXF000'

strategy:
  ema_fast_period: 9
  ema_slow_period: 21
  rsi_period: 14
  max_drawdown: 0.1
  daily_loss_limit: 0.02
  risk_per_trade: 0.01
  lot_size: 1
  max_contracts: 1
  commission_rate: 0.00025
  spread_ticks: 2